---
# tasks file for roles/database
- name: Run Database
  docker_container:
    name: database
    image: davvcpe/my-database:latest
    networks:
      - name: my-network
    state: started
    recreate: true
    pull: true
    volumes:
      - /var/lib/postgresql/data
  vars:
    ansible_python_interpreter: /usr/bin/python3
