version: "3.7"

services:
  backend:
    image: davvcpe/my-backend:1.0
    networks:
      - my-network
    depends_on:
      - database
    environment:
      - DB_URL=database:5432
      - DB_USER=usr
      - DB_PWD=pwd
      - DB_NAME=db

  database:
    image: davvcpe/my-database:1.0
    networks:
      - my-network
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=usr
      - POSTGRES_DB=db

  httpd:
    image: davvcpe/my-httpd:1.0
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    name: my-network
