---
# tasks file for roles/backend
- name: Run App
  docker_container:
    name: backend
    image: davvcpe/my-backend:latest
    networks:
      - name: my-network
    state: started
    recreate: true
    pull: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
