---
# tasks file for roles/proxy
- name: Run Proxy
  docker_container:
    name: proxy
    image: davvcpe/my-httpd:latest
    networks:
      - name: my-network
    ports:
      - "80:80"
    state: started
    recreate: true
    pull: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
