name: Ansible Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Check SSH Connection
        run: ssh -i ssh/id_rsa centos@david.pichard.takima.cloud echo "SSH connection successful!"

      - name: Create Vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ansible/vault-password-file

      - name: Run Ansible playbook
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/firstplaybook.yml ansible/deploy_app.yml --vault-password-file ansible/vault-password-file
