name: build and push docker image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
       - name: Check if test-backend passed
        run: echo "Test Backend Status: ${{ needs.test-backend.result }}"
        id: check-test-status

      - name: Login to DockerHub
        if: steps.check-test-status.outputs.result == 'success'
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./BackendAPI/simple-api-student-main
          tags: ${{secrets.DOCKERHUB_USERNAME}}/my-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./Database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/my-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./HttpServer
          tags: ${{secrets.DOCKERHUB_USERNAME}}/my-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
